### ISSUE TITLE
 DeprecationWarning

### ISSUE THREAD

**Issue by CelestialRose101** [sarsamurmu/anki-offline-sync#2]
I did all the steps but when I run start server it gives an error message and my server on the web says this page cannot be found, 404 error.

Error Message: 

(node:190676) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

How do I fix this?

**Comment by sarsamurmu** [comment]
You are not supposed to open the server link in a browser

**Comment by CelestialRose101** [comment]
Oh.. I didn’t know. But when I press sync on Anki it says that it cannot
sync so does that mean it’s because the server doesn’t work? Does the
server not work on the browser for everyone? Were there steps I was
supposed to take before doing the instructions on the GitHub? Idk why the
sync didn’t work.

Overall I’m confused on how the GitHub server setup is different from
Anki’a self server instructions.

I appreciate your reply.

**Comment by CelestialRose101** [comment]
Also how would I secure it with encryption or reverse proxy?

**Comment by CelestialRose101** [comment]
I figured it out I put the wrong address on anki so now it works! How do I
make it a secure connection? like I asked above? Or is it already secure?

**Comment by sarsamurmu** [comment]
This server is limited only to your local network (WiFi). So if other people are not using the local server then it's already secure.

**Comment by CelestialRose101** [comment]
Ohh okay. Does that mean it will only update if I’m on my own Wi-Fi?

**Comment by sarsamurmu** [comment]
Will work on any WiFi. Also, there is already a password so it's tough to access the server without the correct password. Make the password strong I guess.

**Comment by CelestialRose101** [comment]
Ok, thanks.

**Comment by CelestialRose101** [comment]
ty
